Progress bar.

diff --git a/run_bench b/run_bench
--- a/run_bench
+++ b/run_bench
@@ -31,6 +31,25 @@ For complete documentation, go to ...
 EOF
 }
 
+spin()
+{
+	while ps | grep $1 &>/dev/null; do
+		i=0
+		while [ $i -lt 3 ]; do
+			echo -n "."
+			i=$[$i+1]
+			sleep 0.5
+		done
+		i=0
+		while [ $i -lt 3 ]; do
+    	    echo -ne '\b \b'
+			i=$[$i+1]
+			sleep 0.5
+		done
+    done
+	echo -n '...'
+}
+
 # Display a list with all the available benchmarks.
 list_bms()
 {
@@ -72,7 +91,7 @@ run_bm()
 		otpl=${otp%%=*}
 		otpv=${otp##*=}
 
-		# For each VM argument set.
+		# For each VM args set.
 		for args in $ARGS; do	
 			
 			argsl=${args%%=*}
@@ -105,6 +124,7 @@ run_bm()
 	done
 }
 
+# Do run the benchmark.
 do_run_bm()
 {
 
@@ -152,6 +172,23 @@ EOF
 	fi
 
 	IFS=$MY_IFS
+}
+
+# Perform sanity check on the results of a benchmark.
+check_bm()
+{
+	local succeeded=1
+	NF=`ls -1 $bdir/output/*.output | wc -l`
+	if [ $NF -gt 1 ]; then	
+		BF=`ls -1 $bdir/output/*.output | head -n 1`
+		for f in `ls $bdir/output/*.output`; do
+			if [ ! -z `diff -B -q $BF $f` ]; then
+				succeeded=0
+				break
+			fi
+		done
+	fi
+	return $succeeded
 }
 
 # Plot diagrams for a benchmark.
@@ -250,7 +287,8 @@ plot()
 	rm -rf $sdir/*.tmp
 }
 
-while getopts ":b:hls:n:pi:" opt; do
+# Handle the specified options.
+while getopts ":b:chlm:s:n:pi:" opt; do
 	case $opt in
 		b)
 			BMS=$OPTARG
@@ -288,6 +326,7 @@ while getopts ":b:hls:n:pi:" opt; do
 	esac
 done
 
+# Handle the specified number of schedulers.
 if [ -z $SCS ]; then
 	SCS=`cat /proc/cpuinfo | grep processor | wc -l`
 fi
@@ -308,6 +347,7 @@ L=$(( L - 1 ))
 SCS=${SCS:0:L}
 NSCS=`echo $SCS | tr "," "\n" | wc -l`
 
+# Handle the specified number of nodes.
 if [ -z $NDS ]; then
 	NDS=0
 fi
@@ -324,16 +364,25 @@ L=$(( L - 1 ))
 NDS=${NDS:0:L}
 NNDS=`echo $NDS | tr "," "\n" | wc -l`
 
+# Handle the specified number of iterations.
 if [ -z $ITERATIONS ]; then
 	ITERATIONS=1
 fi
+
+# Handle the mnemonic name.
+if [ -z $MNEMONIC_NAME ]; then
+	MNEMONIC_NAME=`date +%d.%m.%y.-%H.%M.%S`
+fi
  
+# Configure the suite.
 source conf/suite.conf
 
+# These are the default OTP, VM args and cookie. 
 DEF_OTPS=${OTPS:-"DEFOTP="}
 DEF_ARGS=${ARGS:-"DEFARGS= "}
-DEF_COOKIE=${COOKIE:-"scala_cookie"}
+DEF_COOKIE=${COOKIE:-"erl_bench_cookie"}
 
+# If no benchmark has been specified, then run all benchmarks.
 if [ -z "$BMS" ]; then
     for b in `ls bench`; do
         if [ -d bench/$b ]; then
@@ -349,43 +398,71 @@ fi
 OLD_IFS=$IFS
 MY_IFS=$','
 
-if [ -z $MNEMONIC_NAME ]; then
-	NOW=`date +%d.%m.%y.-%H.%M.%S`
-	dir=results/$NOW
-else
-	if [ -e results/$MNEMONIC_NAME ]; then
-		rm -rf results/$MNEMONIC_NAME
-	fi
-	dir=results/$MNEMONIC_NAME
+# Create a new directory in the results directory.
+if [ -e results/$MNEMONIC_NAME ]; then
+	rm -rf results/$MNEMONIC_NAME
 fi
+dir=results/$MNEMONIC_NAME
 mkdir $dir
 
+# For each one of the specified benchmarks.
 IFS=$MY_IFS
 for bench in $BMS; do
+	
+	# There is no benchmark with this name.
 	if [ ! -d bench/$bench ]; then
         echo "Unknown benchmark: $bench"
+
+	# This benchmark must be ignored.
     elif [[ "$IGNORE_BENCH" =~ "$bench" ]]; then
         echo "Ignored benchmark: $bench"
+
+	# Do something about this benchmark.
     else
+
 		echo "Benchmark: $bench"
+
+		# Restore OTP, VM args and cookie to their default values.
 		OTPS=$DEF_OTPS
 		ARGS=$DEF_ARGS
 		COOKIE=$DEF_COOKIE
+
+		# Do the same for the code path and the extra VM args.
 		CODE_PATH=
 		EXTRA_ARGS=
+
 		IFS=$MY_IFS
-		echo "Running..."
-		run_bm
+
+		# Run this benchmark.
+		echo -n "Running"
+		run_bm &
+		spin $!
+		echo " done"
+
 		IFS=$OLD_IFS
+
+		# Perform sanity check on the results of this benchmark.
 		if [ "$SANITY_CHECK" == "1" ]; then
-			echo "Performing sanity check..."
-			check_bm
+			echo -n "Performing sanity check"
+			check_bm &
+			spin $!
+			if [ $? == 1 ]; then
+				echo " succeeded"
+			else
+				echo " failed"
+			fi
 		fi
+
+		# Plot.
 		if [[ ( "$PLOT" == "1" ) && ( ( "$NNDS" -ne "1" ) || ( "$NSCS" -ne "1" ) ) ]]; then
-			echo "Plotting..."
-			plot_bm
+			echo -n "Plotting"
+			plot_bm &
+			spin $!
+			echo " done"
 		fi
 	fi
+
 	IFS=$MY_IFS
+
 done
 
